name: Deploy React App to cPanel Subdomain

on:
  push:
    branches:
      - main # Triggers the workflow on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Ensure this matches your project's Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build the React app
        run: npm run build

      - name: Deploy to cPanel Subdomain
        uses: SamKirkland/FTP-Deploy-Action@4.3.4
        with:
          server: ftp.vidtrail.com
          username: ${{ secrets.CPANEL_USERNAME }}
          password: ${{ secrets.CPANEL_PASSWORD }}
          local-dir: build/
          server-dir: /admin.vidtrail.com/ # Path to your subdomain's directory
          protocol: ftps
