on:
  push:
    branches:
      - main
name: 🚀 Deploy React App to admin.vidtrail.com on Push

jobs:
  web-deploy:
    name: 🎉 Deploy to Subdomain
    runs-on: ubuntu-latest
    env:
      CI: false
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: Use Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: 🔨 Build Project
        run: |
          npm install
          npm run build

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.GIT_CPANEL_REACT_SERVER }}
          username: ${{ secrets.GIT_CPANEL_REACT_USER }}
          password: ${{ secrets.GIT_CPANEL_REACT_PWD }}
          protocol: ${{ secrets.GIT_CPANEL_REACT_PROTOCOL }}
          local-dir: ./dist/ # Change this to ./dist/ to match your actual build directory
          server-dir: /admin.vidtrail.com/
